i1=input('digite algo: ')
print('O tipo primitivo da variável é: {}'.format(type(i1)))
print('É um valor númerico?: {}'.format(i1.isnumeric()))
print('É um valor alfabético?: {}'.format(i1.isalpha()))
print('É um valor alfanúmerico?: {}'.format(i1.isalnum()))
print('É um valor decimal?: {}'.format(i1.isdecimal()))
print('Está todo em Maiúsculo?: {}'.format(i1.isupper()))
print('Está todo em Minúsculo?: {}'.format(i1.islower()))
print('Pode ser impresso?: {}'.format(i1.isprintable()))
print(i1.isdigit())